module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  env: {
    browser: true,
    es2021: true,
    jest: true,
    node: true,
  },
  extends: ['airbnb', 'airbnb-typescript', 'prettier'],
  parserOptions: {
    project: ['./tsconfig.json'],
  },
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
    process: true,
  },
  plugins: ['react-hooks'],
  rules: {
    'react-hooks/exhaustive-deps': 'error',
    'react-hooks/rules-of-hooks': 'error',
    'no-param-reassign': 'off',
    'no-restricted-globals': 'off',
    'react/prop-types': 'off',
    'react/destructuring-assignment': 'off',
    'import/prefer-default-export': 'off',
    'jsx-a11y/anchor-is-valid': 'off',
    'react/state-in-constructor': 'off',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/no-static-element-interactions': 'off',
    'react/jsx-props-no-spreading': 'off',
    'no-template-curly-in-string': 'off',
    'import/extensions': 'off',
    'consistent-return': 'off',
    'import/no-extraneous-dependencies': 'off',
    'react/function-component-definition': 'off',
    'no-restricted-exports': 'off',
    'react/jsx-fragments': 'off',
    'arrow-body-style': 'off',
    'prefer-for-of': 'off',
    'guard-for-in': 'off',
    'no-continue': 'off',
    'max-len': ['error', { code: 125 }],
    'no-restricted-syntax': ['error', { selector: 'LabeledStatement' }, { selector: 'WithStatement' }],
    'react/require-default-props': 'off',
    'react/react-in-jsx-scope': 'off',
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
};
